# Ip of juju-controller (juju tag machine in maas), i.e 192.168.30.60
juju-controller: 192.168.30.18
juju-ca-cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVyVENDQXhXZ0F3SUJBZ0lWQUsyeG9MN0t4
    Y1lITnVydTRCanBMNmsrYmdQME1BMEdDU3FHU0liM0RRRUIKQ3dVQU1HNHhEVEFMQmdOVkJBb1RC
    R3AxYW5VeExqQXNCZ05WQkFNTUpXcDFhblV0WjJWdVpYSmhkR1ZrSUVOQgpJR1p2Y2lCdGIyUmxi
    Q0FpYW5WcWRTMWpZU0l4TFRBckJnTlZCQVVUSkRoaVlqSm1aRGhoTFdKbE1UWXROR0pqCk1DMDRa
    REl3TFdSaE5ETTVOemd4T1RjM1lUQWVGdzB5TURBek1qWXhORFEwTVROYUZ3MHpNREEwTURJeE5E
    UTAKTVRKYU1HNHhEVEFMQmdOVkJBb1RCR3AxYW5VeExqQXNCZ05WQkFNTUpXcDFhblV0WjJWdVpY
    SmhkR1ZrSUVOQgpJR1p2Y2lCdGIyUmxiQ0FpYW5WcWRTMWpZU0l4TFRBckJnTlZCQVVUSkRoaVlq
    Sm1aRGhoTFdKbE1UWXROR0pqCk1DMDRaREl3TFdSaE5ETTVOemd4T1RjM1lUQ0NBYUl3RFFZSktv
    WklodmNOQVFFQkJRQURnZ0dQQURDQ0FZb0MKZ2dHQkFNeUhHSHpEZklXWVZsNS8xQXI1QWsycnhI
    d2cxNnowZzZ4QXJGblBMR0VOMjVrK1VSVFoxT1c5eFUxcApqT05va0gyNjFvQWxSUmhKbUFYbCt0
    Z1ltUVdhckpSckRYVHdQZnp6bDlORU5zbURqUFpRMlNLaFJGQ3kyZ2xDCjhNTnozaUYvMWlZdDds
    U1VuSk9ENXl0eFN1cnh4Y1VPMlVFVE9zeE8vRFVjUHZRVnA4QVczV1MwTGY4OC9tWW0KV090WGpN
    bVhwZDRUclFsOGZyd3hGSnRZNFNzd3Z6NG9ramlTQi90OGh5RTBrNmVLU2N5YkQ1RmdqQlMzZGM4
    bgovbjFGNWlMMGdsZlN0bXBnUmVjeTlseDBieE9WZFJ1RzZPTWNHaG1IaHg1MzN3TUdBZzNTMTNr
    Q01XMTBFanBvCmZIcFF1dndqN3QwTklaSHBtM3VXZXo2VFN6ZFJNNm9IbWJUelM3aThnNy92TTFG
    MGY4KzFmTXR0Q1kvaGNVdUYKQ053QStkK1FqYVk2OTBja0JPTHVFWjZhSmczWkRuQWxUTGtGM1ky
    M0VQdllKOTY1WmgzczdPbk5nWUJwOXQ1aAo2cUFMWkdjNVlIYTlzeHdUSjZBTGRlN1JMMjk1NFpK
    NFRGOFJnV3RaR0E2MENSczJWZXJIVTdEMVBRMStJdElXCmJlUU9Jd0lEQVFBQm8wSXdRREFPQmdO
    VkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWQKQmdOVkhRNEVGZ1FVWXdz
    RFg1ZFNneDJYaWt4YkxsYVpjdlJOckZnd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dHQgpBSFlQcnkw
    VUZEVTk1VnErTFJ6Ky9IVE5jODkvR0FNTFlYMHhHb0JJMVJxN2FlOFZlVS80ZngxdHFYV3R6UHU5
    Ci9zZnByd1RRV0Nqc2g5L1NLR3hXSmR0SStIaEFhMDRHelJhTXFjL3NONXN1dmo1MkFKUFNvRzlN
    Uis4T0FYR1MKSGdiODRDTS9VZm9LWlhvcnR5VlIzeHZObWg1VU5Wc0J3Wk1UaGpGbXNGNmlFb1p1
    dytPQXJZOXJqNXF5ajVpVwpNZWcvR25JNitRSWJ4SHdIMDIwekdsVjhnL2pIMUdQUUh0d2tBZW5u
    TkRUcStnSE9sTm1DZS9nWmVmZmhGK2R1ClR0d1FSVVd5cmZwdTRuYmpqL09tdXNzMHRhZ2pYRmx0
    Ykp1Wi9YLzlnTFhDeWJ2Y0RwZFFuYVFTTWFLa2pBQy8KNmdWV1NPWHRUdUwvWkRaaGU3ejRkcmUv
    ZTl2OVIreUV3VFhpSkV1ZHN6L1RzV2ZDeEdPTHFQeXZLZkFTZkdPLwpYblBZZkh3cmhFV09RYVlG
    cUlOQnhuNVFPYURQVXhIRkdaTzB6d1NkT21mZjEyZ1JDNzE4d3lYbGVrcFFlODNXCjZTbmNWWmpa
    OFc3YzRYQzlERDUvVlVKYmhWZzZtM0JFU1lqck45UU1OQzMvU3FDMWR0eE5OQjhvZmdscE4rcWYK
    S2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
juju-model-id: 1bd09f4b-dca1-4ba1-815a-507e8cb91507
juju-controller-password: c0ntrail123