juju-controller: 192.168.30.18
juju-ca-cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVyVENDQXhXZ0F3SUJBZ0lWQUp4Zkl3Z01y
    R0YvcjAzWkVralZHaHFOZ2txK01BMEdDU3FHU0liM0RRRUIKQ3dVQU1HNHhEVEFMQmdOVkJBb1RC
    R3AxYW5VeExqQXNCZ05WQkFNTUpXcDFhblV0WjJWdVpYSmhkR1ZrSUVOQgpJR1p2Y2lCdGIyUmxi
    Q0FpYW5WcWRTMWpZU0l4TFRBckJnTlZCQVVUSkRnek1ETTBNR0UyTFRrek1EZ3ROR0l6ClpDMDRZ
    MkpqTFRFMU1EQmlaV1U0TldObU5EQWVGdzB5TURBek1qTXdOelE0TURCYUZ3MHpNREF6TXpBd056
    UTQKTURCYU1HNHhEVEFMQmdOVkJBb1RCR3AxYW5VeExqQXNCZ05WQkFNTUpXcDFhblV0WjJWdVpY
    SmhkR1ZrSUVOQgpJR1p2Y2lCdGIyUmxiQ0FpYW5WcWRTMWpZU0l4TFRBckJnTlZCQVVUSkRnek1E
    TTBNR0UyTFRrek1EZ3ROR0l6ClpDMDRZMkpqTFRFMU1EQmlaV1U0TldObU5EQ0NBYUl3RFFZSktv
    WklodmNOQVFFQkJRQURnZ0dQQURDQ0FZb0MKZ2dHQkFNS1dFM3RrRVdWUjNYdnRnM1NaQ1hZaXNK
    eGF4SlpaV0lGNm1RNDc3Y1p5Y2ptdDlpdVlaemI4NGxhbQppaHJlUHJoWGR2TWJHQjZXNHBmN2hL
    QVhnV3c5cFVHOVRYSXpJbzJBcUtlU2FqamFmZlhaVy9GaFNUZHR0ZHNLCnZUWkNCYWRYeE5IdXNM
    RW1JRzlJWnhTN1FNYVgyWmplaHI5VWtTOUd5RnRkRDh4SGxhaXFZMnpwakFJZWFVcHYKYUNaWTFN
    UTBleXplWVhJYlJOU0N2b1lNNGJOZkhMYzhPTVRWc3ViQXN3MXY1eVpkS0FmeEFIdDNIR0ZzZ0p3
    ZAppR2JTVTh0bFl5L0JmODhNbnk0d1lFbGU3WUxxT1RxMm9YdVk1K1NWbUJKZ1ppczVqdUVlQ0RW
    enlIR3pPdFB6CmRDaC9kM3l6STJhM2ZZbjhzVzE4V1ZHc0RlcktNMFprRFNOZmxnN09meHVMaTFE
    WnRTNmd4Z2ZQNHU0QlhkcnAKYmczcjZzMm5mUmZxeDBEMVRNU0Q3dG9DcXVWbnpHOE1vWjY0d3RD
    RlV1N3luc0xleWh6LzUrdTlNdVVsMGFudQo5U3czK3d6WFRveEcrLzVac2x6WHE1UG1PL0RhSWw4
    QUZ5Q0U4M0JqK3Q5eG12WmFNeUFPU0hBbStBbk0zNm4xCnlTcHdmd0lEQVFBQm8wSXdRREFPQmdO
    VkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWQKQmdOVkhRNEVGZ1FVLy9n
    WmRzOHQrTVR1Yi92cC9GbG9aMy8ybWs0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dHQgpBQUJNdGJ5
    TnFKbkJBSExUdmxENlQrcXRUdkNkYXgwMDZjRDhKL0hwQkY3ZWJyMmUvY1o5QnJuektaR01LdzU2
    ClBBU3V5RmJ0MUhtVitTdHlHeUJpUFh6NmVhcHdPWU1vRjlpSWQxRWZpb2JwbHZKUUprY3BQQzZl
    R0RXQm9vVXMKU00yR2M4VUx5blo3c0lyMCt3RWJ2Y3Jhc21udFZUL1FwbHhuSFFMWVBnbGx6QTR2
    WlRFcy80UWh2Yy9uUENHYgp4RnIvL2VURVJTTkgzUlljd3ZBTXVVZTE1bitzdEY1MVMvWjhLd2l6
    dE5sbkg2SWVxNlkyMm5tMjdOYUNpQlBxCm1jNXoyT21aUnU3UWgrV3JyWnlvQ2NZZ3VBTjRXLzVh
    ZEFHbHBnaE9NbEdLN29uQnY5SDNKRTQ3V21yS1NPUkYKVi9qOEZCT1FiVVVLUEQ5NklldEp6QVpu
    TEZiY2poVmd1MnNpUWhrdldlSzMrWlRSYlI5QXFIMmZXRkZJcUQ4YQpvM3loZldWaEwxc1JCdUhJ
    cjlmRUZKVGNQdE5EcjhvQ0c5SDZINVRiOGNBdjN6aTBUbm1XRTZFck02a2Q2VmpuCkFKVVZpYW4z
    T1pDWE5aNWoxTEVsZzlZN0t6Y01tbHVPemtCd3poK0Mxc0R2ajVxQ0dTcFFHVDdOUG1EdEFscksK
    ZVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo=

juju-model-id: 4a62e0b0-bcfe-4b35-8da7-48e55f439237
juju-controller-password: password