juju-ca-cert: |
  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4ekNDQWx1Z0F3SUJBZ0lVTkVrRDQ1aXFK
  YzhYS1FqN29MaVpHWDRmV24wd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURU5NQXNHQTFVRUNoTUVT
  blZxZFRFUU1BNEdBMVVFQXhNSGFuVnFkUzFqWVRBZUZ3MHlNVEF6TWpRdwpOelV5TVRoYUZ3MHpN
  VEF6TWpRd056VTNNVGhhTUNFeERUQUxCZ05WQkFvVEJFcDFhblV4RURBT0JnTlZCQU1UCkIycDFh
  blV0WTJFd2dnR2lNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJqd0F3Z2dHS0FvSUJnUUR0OW0wcE4v
  R3UKTXQvZ2cyNjNldW9leHNCaEdsem92TkxWdy9LQVBWczRvb25vMGlmc1ZSNHBNRkE5MFQyMTZL
  Ty9qWGlkdHJmRApsWnpiYll0UDVwN1IzdVJxUWJLTFRyUWl6OFJjWHlLcVlVZ1FmcDhxci9NVTR3
  ZXIzeEFrK1FTaXFTMU5INlpyClhWZHp3cnhVMng5TDhCT09hUitVN3Zzcmc1S1RiTDR6VldiNmhQ
  T2RoRVcrY1NxMlBTRWdCckY2NEN6Mi9MdWgKMHc5Qll0RFpyTG1KcHJBQnZuVkloc2t1REE4bnZS
  b0dPNlVmZWtoNG5uZ0ZGbGtrYzcvc1RKNHhyekZtWWZwTQpYTVpSREdOU2sxWXBDblZGeE4xdUdR
  MTVIRVBNV1hDUGg1MHJvUnhEWFRjMThzZzlnUzJxQmpTd2FZMzNIS09QClpvaU96TkRNL1FIRDVZ
  WlJ4RStIeGRDMEtIQnpuQXVKOU1nUjhKbGpaVEZaQ2FEbzBuQWRpbjh4VFdmQUFqUlUKTG1iVG9J
  bTRLS1k4Sjluc3dpbjRPdlFQUnhjRHN1YkoybWJUMlBaK3BTVFRhN0grS1Bob3ppVDlCZFNwRjBF
  MQpPb0hsZTU4a0dpVWl5ZmRvMzdGWXIvWGtyVVRIRmU3MmJpdTVkSGlNalJ1ejd4cEZnWFAvcnVr
  Q0F3RUFBYU1qCk1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4
  d0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnR0JBTjBLdU9HMTZnK1laRDhmZmpsYk9pa09NODVGSDZR
  QmJEellLK0lvVUI1TE5VUzcrcUZMMFBhTgp2eVdNWlFiNDFyM0dTYXJBOGliMVN5a3c5YlFiYWNC
  L1pMcTg3Z3gxYmxEZlArVmh3QzBZUk9EZlZmMm1YK2c4CkxOdmY1M29sTXg0Z2hpaUpHTzZCQXVQ
  Um12RW1MVVg4SGZibWpWQTRPV0tzcHJBN01vVTZEOFpzZmRpQnRWMXgKVktpS2JYM24zTC9xNmVB
  VU8rbVN6azQzbllNM0IyYUtUa3ZtQVpqZFp4akpLQzVOV2trcGFoUkIrSHpORmRkbQpXNVo5R2Zj
  c25KWmFkZEp2SzlqMXpXeTJIY1VRYWhtN2NHWXpkWTVhQWFGZ0t1bEhhcGRtaGRkUWUvUEh2UDYy
  CmE2L0p1N3MwM1hoWjZrcUsxRFdCb1pXdlA3a3Y4OGorNEV3anI5bks1M1c3cmY3RFhtS2lRWWpx
  ZUorNThQaWoKcFlwZmgvZnlmVWZIRE1Fa0ZDeXFENFA1TWVqU3RPZmtzL3QwMEpmaWdsN2ZpOUdH
  THRGeThNOW1UZ0dmb3AwdAoxdTRacnI2cHo3K0NOQWxibEVyWlArQW9ZODJpSVF5MEpTUU9LZFFM
  SmNLOVdFZUQrMHJHenlENnRaN1hYTERDCjBIMXdXQ3JqcWc9PQotLS0tLUVORCBDRVJUSUZJQ0FU
  RS0tLS0tCgo=
juju-controller: 192.168.7.30
juju-controller-password: c0ntrail123
juju-model-id: e789256c-9e1e-4424-8022-90c7fe9a3873
